---
title: "Regression_group_project"
author: "Group 6"
date: "April 14, 2019"
output: html_document
---

```{r}
dataset <- read.csv("./weekly_stats_2016_nonzero_perc.csv")
```

```{r}
#lm_revenue <- lm(revenue~.-X-sampleId, data = dataset)
#summary(lm_revenue)
#plot(lm_revenue$residuals, col="blue")
```

```{r}
library(MASS) 
library(glmnet) 
library(dplyr)
library(fastDummies)
library(DAAG)
set.seed(95845)  

quantiles = quantile(dataset$revenue)
maxval = quantiles[2] + 1.5 * (quantiles[2]-quantiles[1])
dataset = dataset %>% filter(revenue <= maxval)

company_binary <- fastDummies::dummy_cols(dataset[3])
newdata <- data.frame(dataset, company_binary)


# Split data into train and test sets
n <- nrow(newdata)
train_rows <- sample(1:n, 0.5*n)
x <- newdata %>% dplyr::select(-X,-sampleId,-company,-revenue,-company.1) %>% data.matrix()
y <- newdata %>% dplyr::select(revenue) %>% data.matrix()
x.train <- x[train_rows, ] 
x.test <- x[-train_rows, ] 
y.train <- y[train_rows,] 
y.test <- y[-train_rows,] 

lm_train <- data.frame(x.train,y.train)
lm_test <- data.frame(x.test)

## linear regression
lm_revenue <- lm(y.train~., data = lm_train)
print(summary(lm_revenue))

yhat_lm <- predict(lm_revenue, newdata =  lm_test)
mse_lm <- mean((y.test - yhat_lm)^2)

## cv linear regression

cv_lm <- CVlm(form.lm = y.train~., data = lm_train, m= 10)

mse_cv_lm <- mean((y.test - cv_lm$cvpred)^2)
mse_cv_lm


## Lasso
lasso_fit_cv <- cv.glmnet(x.train, y.train, type.measure="mse", 
                                              alpha=1,family="gaussian")

plot(lasso_fit_cv, main="LASSO")

coef(lasso_fit_cv, s =lasso_fit_cv$lambda.min)

lasso_yhat_cv <- predict(lasso_fit_cv, s=lasso_fit_cv$lambda.min, newx=x.test)

mse_lasso_cv <- mean((y.test - lasso_yhat_cv)^2)

mse_lasso_cv %>% print()

## Ridge

ridge_fit_cv <- cv.glmnet(x.train, y.train, type.measure="mse", alpha=0,family="gaussian")

plot(ridge_fit_cv, main="Ridge")

coef(ridge_fit_cv, s =ridge_fit_cv$lambda.min)

ridge_yhat_cv <- predict(ridge_fit_cv, s=ridge_fit_cv$lambda.min, newx=x.test)

mse_ridge_cv <- mean((y.test - ridge_yhat_cv)^2)

mse_ridge_cv %>% print()

```

```{r}
data.frame(mse_lm,mse_cv_lm, mse_lasso_cv,mse_ridge_cv)
```

